Repository TeamTangerine/TT, pull requests merged in 2025-09, with the labels that each got.

#4 feat/ addProduct마크업
  React/src/pages/addproduct/AddProduct.tsx
Labels: enhancement

#5 feat/profileModification 마크업
  React/src/pages/profileModification/ProfileModification.tsx
Labels: enhancement

#6 Feat/footer header 마크업과 스타일링
  React/src/components/Footer.tsx
  React/src/components/Footer/Footer.tsx
  React/src/components/Footer/component/NavButton.tsx
  React/src/components/Header.tsx
Labels: enhancement

#7 refactor/ 중복되는 태그들 컴포넌트로 변경
  React/src/pages/profileModification/ProfileModification.tsx
  React/src/pages/profileModification/components/TextInput.tsx
Labels: enhancement

#8 feat/ homepage 스타일링 작성, footer 겹침 문제 수정
  React/src/components/Footer/Footer.tsx
  React/src/pages/home/HomePage.tsx
Labels: enhancement

#9 feat/post페이지 마크업 구현 완료
  React/src/components/Posting.tsx
  React/src/pages/post/Post.tsx
  React/src/pages/post/components/Comment.tsx
  React/src/pages/profileModification/ProfileModification.tsx
  React/src/pages/profilemodification/ProfileMod.tsx
Labels: enhancement

#13 Feat/login-email : "Login-WIth-Email" 페이지 작업 완료
  React/src/pages/Login/Login.tsx
  React/src/pages/Login/LoginWithEmail.tsx
  React/src/pages/Login/components/EmailLogin.tsx
  React/src/pages/Login/components/LoginSignUpForm.tsx
Labels: enhancement

#14 Feature/upload&modal html
  React/src/assets/modal-bar.png
  React/src/components/modal/Modal.tsx
  React/src/pages/upload/Upload.tsx
Labels: enhancement

#17 feat/textInput컴포넌트 마크업,css 작성
  React/src/assets/img-button.png
  React/src/components/TextInput.tsx
  React/src/pages/profileModification/ProfileModification.tsx
  React/src/pages/profileModification/components/TextInput.tsx
Labels: enhancement

#22 fix/이미지 버튼 원본으로 교체
  React/src/assets/img-button.png
Labels: bug

#19 Feat/user profile컴포넌트, 유저조회 서비스 작성
  React/src/components/UserProfile.tsx
  React/src/service/getUserProfile.ts
  React/src/types/IUserProfileProps.ts
Labels: enhancement

#24 Feature/profile&post&upload 페이지 css작업
  React/src/components/TextInput.tsx
  React/src/pages/chat/ChatList.tsx
  React/src/pages/chat/ChatRoom.tsx
  React/src/pages/post/Post.tsx
  React/src/pages/post/components/Comment.tsx
  React/src/pages/profileModification/ProfileModification.tsx
  React/src/pages/upload/Upload.tsx
Labels: enhancement

#25 feat/service-user-login login fetch 함수 작업
  React/src/service/user/postLogin.ts
Labels: enhancement

#26 Feat/service user User API 작업 완료
  React/src/service/user/getProfile.ts
  React/src/service/user/postEmailValid.ts
  React/src/service/user/postIdValid.ts
  React/src/service/user/postLogin.ts
  React/src/service/user/postMembership.ts
  React/src/types/IButtonType.ts
Labels: enhancement

#40 Feat/ap iservice fetch관련함수 로직 작성
  React/src/service/fetch/api.ts
  React/src/service/fetch/fetcher.ts
  React/src/service/fetch/https.ts
  React/src/types/IFetchType.ts
  React/src/types/IOptionsType.ts
Labels: enhancement

#42 Feat/footer 기능구현
  React/src/components/Footer/Footer.tsx
  React/src/components/Footer/component/NavButton.tsx
Labels: enhancement

#45 feat/snslogin 버튼 클릭시 알림 추가
  React/src/pages/Auth/components/SNSLogin.tsx
Labels: enhancement

#50 Feature/header of chat
  React/src/pages/chat/ChatList.tsx
  React/src/pages/chat/ChatRoom.tsx
Labels: enhancement

#47 Feature/join membership
  React/src/Utils/validation.ts
  React/src/components/TextInput.tsx
  React/src/pages/Auth/JoinMembership.tsx
  React/src/pages/Auth/MembershipProfile.tsx
  React/src/pages/Auth/components/LoginSignUpForm.tsx
Labels: enhancement

#49 Feat/product업로드 기능구현
  React/src/Utils/validation.ts
  React/src/components/Header.tsx
  React/src/components/TextInput.tsx
  React/src/pages/myprofile/AddProduct.tsx
  React/src/pages/upload/Upload.tsx
  React/src/service/fetch/api.ts
Labels: enhancement

#56 Feature/home page
  React/src/components/Posting.tsx
  React/src/pages/home/HomePage.tsx
Labels: enhancement

#58 Refactor/button,header에 따른 기존 컴포넌트 수정
  React/src/components/Header.tsx
  React/src/pages/myprofile/AddProduct.tsx
Labels: bug

#62 Feature/posting component for post page
  React/src/App.jsx
  React/src/Utils/validation.ts
  React/src/components/Posting.tsx
  React/src/pages/Auth/components/LoginSignUpForm.tsx
  React/src/pages/home/HomePage.tsx
  React/src/types/IFetchType.ts
Labels: enhancement

#61 Refactor/chat list 중앙 정렬, 링크 이동 수단 변경
  React/src/pages/chat/ChatList.tsx
Labels: documentation

#60 refactor/product list 디자인 수정
  React/src/components/profile/Product.tsx
  React/src/components/profile/ProductList.tsx
Labels: enhancement

#64 Feat/posting-grid
  React/src/components/Posting.tsx
  React/src/components/PostingGrid.tsx
  React/src/components/profile/Heart.tsx
Labels: enhancement

#76 feat/회원 가입 시 유저 프로필 기본 이미지 설정해주기
  React/src/pages/Auth/components/LoginSignUpForm.tsx
Labels: documentation

#75 fix/add-product 상품 이름 등록 - 정규표현식 수정
  React/src/pages/myprofile/AddProduct.tsx
Labels: bug

#82 Feature/throttle 함수 리팩토링과 무한 스크롤 함수 구현
  React/src/Utils/infiniteScroll.ts
  React/src/Utils/throttle.ts
  React/src/pages/post/Post.tsx
Labels: enhancement

#83 refactor/posting grid Posting 컴포넌트 라인클램프 적용여부를 useRef 훅을 이용하는 것으로 수정
  React/src/components/Posting.tsx
  React/src/components/PostingGrid.tsx
Labels: enhancement

#78 Refactor/login sign up form 리팩토링
  React/src/pages/Auth/components/LoginSignUpForm.tsx
Labels: enhancement

#85 fix/follow-list 필요없는 상수 및 필요없는 에러값 정리
  React/src/App.jsx
  React/src/components/Button/FollowToggleButton.tsx
  React/src/components/Posting.tsx
  React/src/components/profile/UserInfo.tsx
  React/src/pages/followers/FollowList.tsx
  React/src/types/IFollowToggleButtonType.ts
Labels: bug

#87 feat/공통 버튼 컴포넌트에 throttle 함수 적용
  React/src/components/Button/Button.tsx
  React/src/components/Button/FollowToggleButton.tsx
Labels: enhancement

#88 fix/product-list 상품목록 렌더링 오류 수정 / 모달창 오류 수정 / 기본 이미지 설정 오류 수정
  React/src/components/profile/Product.tsx
  React/src/components/profile/ProductList.tsx
Labels: bug

#89 Feature/throttle scroll
  React/src/Utils/infiniteScroll.ts
  React/src/pages/post/Post.tsx
Labels: enhancement

#81 Refactor/프로필관련컴포넌트 정리,누락되거나 잘못된 함수 정리,경로 정리
  React/src/App.jsx
  React/src/components/PostingGrid.tsx
  React/src/components/UserProfile.tsx
  React/src/components/profile/ProductList.tsx
  React/src/pages/myprofile/AddProduct.tsx
  React/src/pages/myprofile/ProfileModification.tsx
  React/src/pages/search/SearchPage.tsx
  React/src/pages/yourprofile/YourProfile.tsx
Labels: bug, enhancement
